/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TermsIndexImport } from './routes/terms/index'
import { Route as SpeakerIndexImport } from './routes/speaker/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as PublicIndexImport } from './routes/public/index'
import { Route as PrivacyIndexImport } from './routes/privacy/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TermsIndexRoute = TermsIndexImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRoute,
} as any)

const SpeakerIndexRoute = SpeakerIndexImport.update({
  id: '/speaker/',
  path: '/speaker/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  id: '/public/',
  path: '/public/',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyIndexRoute = PrivacyIndexImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyIndexImport
      parentRoute: typeof rootRoute
    }
    '/public/': {
      id: '/public/'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/speaker/': {
      id: '/speaker/'
      path: '/speaker'
      fullPath: '/speaker'
      preLoaderRoute: typeof SpeakerIndexImport
      parentRoute: typeof rootRoute
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/public': typeof PublicIndexRoute
  '/register': typeof RegisterIndexRoute
  '/speaker': typeof SpeakerIndexRoute
  '/terms': typeof TermsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/public': typeof PublicIndexRoute
  '/register': typeof RegisterIndexRoute
  '/speaker': typeof SpeakerIndexRoute
  '/terms': typeof TermsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/public/': typeof PublicIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/speaker/': typeof SpeakerIndexRoute
  '/terms/': typeof TermsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/public'
    | '/register'
    | '/speaker'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/public'
    | '/register'
    | '/speaker'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/login/'
    | '/privacy/'
    | '/public/'
    | '/register/'
    | '/speaker/'
    | '/terms/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  PublicIndexRoute: typeof PublicIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  SpeakerIndexRoute: typeof SpeakerIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  PublicIndexRoute: PublicIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  SpeakerIndexRoute: SpeakerIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard/",
        "/login/",
        "/privacy/",
        "/public/",
        "/register/",
        "/speaker/",
        "/terms/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/privacy/": {
      "filePath": "privacy/index.tsx"
    },
    "/public/": {
      "filePath": "public/index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/speaker/": {
      "filePath": "speaker/index.tsx"
    },
    "/terms/": {
      "filePath": "terms/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
